// Launched by capture.py. Ego's embedded process does not inherit the shell cwd or env.
const configuration = globalThis.store2CaptureConfig;
if (!configuration?.root || !configuration?.spaceId) throw new Error('Use capture.py with an existing TaskSpace id.');
const fs = await import('node:fs/promises');
const path = await import('node:path');
const os = await import('node:os');
const base = configuration.url || 'http://127.0.0.1:4186/store2/';
const task = await taskSpace(configuration.spaceId);
console.log({ spaceId: task.spaceId });
const page = task.page('p1');
const output = path.join(configuration.root, 'store2');
await page.cdp('Network.enable');
await page.cdp('Network.setCacheDisabled', { cacheDisabled: true });
const viewport = async (width, height) => page.cdp('Emulation.setDeviceMetricsOverride', { width, height, deviceScaleFactor: 1, mobile: false });
const ready = async () => page.waitForSelector('html[data-capture-ready]');
for (const [name, width, height, format] of [
  ['banner-1544x500.png', 1544, 500, 'banner'],
  ['card-1200x630.png', 1200, 630, 'card']
]) {
  await viewport(width, height);
  await page.goto(`${base}?export=${format}&lang=fr`);
  await ready();
  await page.screenshot({ path: path.join(output, 'assets', name) });
}
await viewport(1440, 900);
await page.goto(`${base}?lang=fr`);
await ready();
await page.screenshot({ path: path.join(output, 'screenshots', '01-store2-desktop.png'), fullPage: true });
await viewport(390, 844);
await page.screenshot({ path: path.join(output, 'screenshots', '02-store2-mobile.png'), fullPage: true });

// Production UI fixture: actual HTML/CSS/JS, generated by prepare-capture.py.
await viewport(1280, 800);
await page.goto(`${base}media-kit/production.html`);
await page.waitForSelector('html[data-capture-ready]');
await page.screenshot({ path: path.join(output, 'screenshots', '03-app-empty-1280x800.png') });
await viewport(1600, 1000);
await page.setInputFiles('#fileInput', [path.join(output, 'assets', 'botanical.png')]);
await page.waitForFunction(() => document.querySelector('#fullscreenProgressPercent').textContent === 'Télécharger' && document.querySelector('#fullscreenResultImg').naturalWidth > 0);
await page.screenshot({ path: path.join(output, 'screenshots', '04-app-result-fixture-1600x1000.png') });

const frameDirectory = await fs.mkdtemp(path.join(os.tmpdir(), 'imgralph-store2-frames-'));
await viewport(1280, 720);
await page.goto(`${base}?export=video&lang=fr`);
await ready();
for (let index = 0; index < 192; index++) {
  await page.evaluate(time => window.store2.seekDemo(time), index / 24);
  await page.screenshot({ path: path.join(frameDirectory, `${String(index).padStart(4, '0')}.png`) });
}
console.log({ frameDirectory, fps: 24, duration: 8, output });
await page.goto(`${base}?lang=fr`);
// The caller owns the TaskSpace lifecycle, so captures can be visually reviewed before finish().
